GET http://localhost:8080/api/assets/treasure.png
Content-Type: application/json
Authorization: Bearer <token>

###
POST http://localhost:8080/api/logout
Content-Type: application/json
Authorization: Bearer <token>

{
  "username": "py",
  "password": "python1"
}
###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username": "py",
  "password": "python1"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "py",
  "password": "python1"
}

###
GET http://127.0.0.1:8080/docs